
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/todo?serverTimezone=Asia/Seoul
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update #create update none
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        format_sql: true
  application:
    name: todo

logging:
  level:
    org:
      springframework:
        security: trace

app:
  jwt:
    secret: byulSoftTodo