
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/todo?serverTimezone=Asia/Seoul
    username: root
    password: root

  application:
    name: todo

app:
  jwt:
    secret: byulSoftTodo


mybatis:
  type-aliases-package: org.min.todo.dto
  mapper-locations: mybatis-mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true