
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mybatisTodo?serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: root
    password: root
#    spring.datasource.schema: data/schema.sql

  application:
    name: todo
#  sql:
#    init:
#      mode: always

app:
  jwt:
    secret: byulSoftTodo


mybatis:
  type-aliases-package: org.min.todo.dto
  mapper-locations: mybatis-mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

